version: '3.8'

services:
    back_end:
        image: psppx/team-14-backend:${VERSION:-latest}
        ports:
            - 4141:3000
        environment:
            - PORT=3000
            - MODE=DEV
            - POSTGRES_HOST=178.128.60.199
            - POSTGRES_PORT=5432
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=pwmoodment
            - POSTGRES_DATABASE=dev_moodment
            - POSTGRES_SYNC="false"
            - POSTGRES_DROP_SCHEMA="false"
            - JWT_SECRET="eyJhbGciOiJIUzI1NieyJSb2xlIjoiQWRtaW4iLCJJc3N1ZXIiOiJJc3N1ZXIiLCJVc2VybmFtZSI6IkphdmFJblVzZSIsImV4cCI6MTY0NDMwNzEyNywiaWF0IjoxNjQ0MzA3MTI3fQ4"
            - JWT_ACCESS_TOKEN_LIFE="1d"
            - JWT_REFRESH_TOKEN_LIFE="30d"
            - BCRYPT_SALT_ROUNDS=8
    front_end:
        image: psppx/team-14-frontend:${VERSION:-latest}
        ports:
            - 1414:80