version: '3.8'

services:
    back_end:
        image: psppx/final:${VERSION:-latest}
        build:
            context: ./backend
            target: production
            dockerfile: ./Dockerfile
    front_end:
        image: psppx/final:${VERSION:-latest}
        build:
            context: ./frontend
            target: production
            dockerfile: ./Dockerfile