version: '3.8'

services:
    back_end:
        image: psppx/final:${VERSION:-latest}
        ports:
            - 4141:8080
        environment:
            - PORT=8080
            - MODE=production
            - POSTGRES_HOST=206.189.38.174
            - POSTGRES_PORT=15432
            - POSTGRES_USER=pleng
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DATABASE=dEE71D5DCCFA3Aev_moodment
            - POSTGRES_SYNC="false"
            - POSTGRES_DROP_SCHEMA="false"
    front_end:
        image: psppx/final:${VERSION:-latest}
        ports:
            - 1414:80